import { generateObject } from "@/services/ai/runtime";
import type { DiscoveryContext } from "../discovery/load-context";
import { formatDiscoveryContextForPrompt } from "../discovery/load-context";
import { MarketSynthesisSchema, type MarketSynthesis } from "./schema";

export const SYSTEM = `You are AutoScale's Competitor Intelligence Synthesizer. You perform the deep "pondering" pass over all gathered evidence.

You produce a structured market understanding for a specific founder. Think hard about patterns that repeat across multiple competitors and what is transferable to THIS product.

EVIDENCE TYPES TO USE:
- Basic sources: title, snippet, URL, platform
- Deep enrichment (when present): positioning statements, pricing signals, CTA patterns, key features, key benefits, content themes, repeated terms, social links, crawled page URLs
- Use deep enrichment positioning/features/CTAs as primary evidence for competitor profiles when available

Hard rules (protect the evidence chain):
- Separate observed evidence from strategic inference. Mark inference clearly in caveats.
- Every competitor profile and market pattern must cite evidence_urls drawn ONLY from the gathered sources provided. Do not invent URLs, handles, metrics, or competitors.
- Pricing, CTAs, features, and positioning must ONLY be stated if present in deep enrichment data or explicit source snippets. Do not hallucinate.
- Never state performance (views, virality, growth) as fact unless the evidence explicitly shows it; otherwise add a caveat and lower confidence.
- Prefer patterns confirmed across multiple sources. A pattern seen once is low confidence.
- transferability is 0-1 for how applicable a pattern is to this founder's product, ICP, and pain.
- white_space = angles/formats the audience cares about that competitors underuse.
- suggested_opportunities = intelligence gaps or distribution angles worth studying later. Do NOT propose content experiments, posts, hooks to publish, or A/B tests.
- If evidence is thin, say so honestly with low overall_confidence and explicit caveats. Do not pad.
- Return JSON matching the schema.`;

export interface SynthesizeFindingsInput {
  context: DiscoveryContext;
  evidenceDigest: string;
  hypotheses: string[];
}

export interface SynthesizeFindingsResult {
  synthesis: MarketSynthesis;
  usedFallback: boolean;
  provider: string;
  model: string;
  latencyMs: number;
}

export async function synthesizeFindings(
  input: SynthesizeFindingsInput
): Promise<SynthesizeFindingsResult> {
  const hypothesesBlock = input.hypotheses.length
    ? input.hypotheses.map((h) => `- ${h}`).join("\n")
    : "(none recorded)";

  const prompt = `[[source_discovery]]
Synthesize competitor intelligence for this founder from the gathered evidence.

PRODUCT CONTEXT:
${formatDiscoveryContextForPrompt(input.context)}

WORKING HYPOTHESES FROM THE RESEARCH LOOP:
${hypothesesBlock}

GATHERED EVIDENCE (discovered + fetched sources — cite these URLs only):
${input.evidenceDigest || "(no usable evidence was gathered)"}

Produce the structured synthesis. Consolidate sources into competitor/account profiles, extract repeated market patterns with transferability, and identify white space. Note suggested opportunities only as intelligence follow-ups — not experiments. Be rigorous about confidence and caveats.`;

  try {
    const result = await generateObject({
      system: SYSTEM,
      prompt,
      schema: MarketSynthesisSchema,
      schemaName: "MarketSynthesis",
      taskType: "discovery_reasoning",
      temperature: 0.4,
      maxTokens: 6000,
    });

    return {
      synthesis: result.object,
      usedFallback: false,
      provider: result.provider,
      model: result.model,
      latencyMs: result.latencyMs,
    };
  } catch {
    return {
      synthesis: {
        summary:
          "Deep synthesis could not be generated by the reasoning model. Source candidates were still gathered and saved for review.",
        competitors: [],
        market_patterns: [],
        white_space: [],
        suggested_opportunities: [],
        overall_confidence: "low",
        caveats: ["AI synthesis unavailable — review the gathered source candidates manually."],
      },
      usedFallback: true,
      provider: "deterministic",
      model: "fallback",
      latencyMs: 0,
    };
  }
}
